### ISSUE TITLE
Can't Finish PHONEMIZING On Google Colab.

### ISSUE THREAD

**Issue by The-Sad-Zewalian** [as-ideas/TransformerTTS#139]
I am trying to run the training code on google colab using GPU. When I run create_training_data.py on ljspeech, The RAM goes to almost 100% and always reach 30% 3964/13100 [12:32<132:40:03, 52.28s/it].

**Comment by The-Sad-Zewalian** [comment]
And yes, If I leave it, this error occurs.

PHONEMIZING
 30% 3972/13100 [24:59<211:47:24, 83.53s/it]/tmp/tmpeqtkupx7/libespeak.so.1.1.48: failed to map segment from shared object
File id LJ008-0100
 30% 3973/13100 [26:30<1:00:54,  2.50it/s]  
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/content/TransformerTTS/create_training_data.py", line 145, in process_phonemes
    phon = text_proc.phonemizer(text)
  File "/content/TransformerTTS/data/text/tokenizer.py", line 66, in __call__
    phonemes = phonemize(text,
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/phonemize.py", line 206, in phonemize
    phonemizer = BACKENDS[backend](
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/espeak/espeak.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/espeak/base.py", line 39, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/base.py", line 83, in __init__
    self.name(), '.'.join(str(v) for v in self.version()))
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/espeak/base.py", line 108, in version
    return EspeakWrapper().version
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/espeak/wrapper.py", line 60, in __init__
    self._espeak = EspeakAPI(self.library())
  File "/usr/local/lib/python3.10/dist-packages/phonemizer/backend/espeak/api.py", line 84, in __init__
    self._library = ctypes.cdll.LoadLibrary(str(espeak_copy))
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/tmpeqtkupx7/libespeak.so.1.1.48: failed to map segment from shared object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/dist-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/content/TransformerTTS/create_training_data.py", line 148, in process_phonemes
    raise BrokenPipeError
BrokenPipeError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/TransformerTTS/create_training_data.py", line 155, in <module>
    for (file_id, phonemes) in phon_iter:
  File "/usr/local/lib/python3.10/dist-packages/p_tqdm/p_tqdm.py", line 54, in _parallel

File id LJ025-0141
    for item in tqdm_func(map_func(function, *iterables), total=length, **kwargs):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/dist-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/content/TransformerTTS/create_training_data.py", line 148, in process_phonemes
    raise BrokenPipeError
BrokenPipeError


What am I doing wrong exactly? Should I have used a portion of the data?

**Comment by The-Sad-Zewalian** [comment]
It turns out it was the phonemizer I downgraded it with
```bash
pip install phonemizer==2.2.0
```
And the issue was solved.

I am extremely sorry for the inconvenience.
