### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#26]
Hi, I frequently get the following error message during training `RuntimeError: main thread is not in main loop` which appears in tkinter's `__init__.py`. "Frequently" means roughly every 20000 steps.

Are you familiar with this error? I'm training on a centos 7 with cuda 10.1 using a single nvidia titan rtx.

**Comment by cfrancesco** [comment]
I haven't seen this error before.
tkinter isn't part of this package, if you're using custom code you'd have to show it.

**Comment by padmalcom** [comment]
I don't and I'm using a fresh python 3.6 environment. When I look for my pip packages I cannot find tkinter. Nevertheless, it throws an error and it is in the lib directory of my environment...

**Comment by cfrancesco** [comment]
I see, and you're using the default training script?
Could you post the entire error log the pip freeze output?

**Comment by padmalcom** [comment]
I found out that the error occurs regularily after 26000 steps. Some hints were given on stackoverflow that the error is linked to matplotlib, but I can't find any reference.

To your questions:
- Yes, I'm running the default training script.
- This is the log output:
TRAINING
```
step 560000:   0%|                                                                                                                                                                      | 0/340000 [00:00<?, ?it/s2020-06-20 19:15:57.675362: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-20 19:15:58.026578: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
step 586013:   8%|███████████▍                                                                                                                                         | 26013/340000 [2:36:03<34:56:59,  2.50it/s]Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c61c198>>
Traceback (most recent call last):279243475
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c2270b8>>
Traceback (most recent call last):44992315769195557 (took 1.67s)                                                                                                                                                   
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop                                                                                                                                                                      
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c2279b0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c21ff98>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4c27550>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4e32160>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4c87668>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4dce780>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c2276d8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c21f400>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4df14e0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a51c3b00>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a50f8c18>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4d20908>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4cae780>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4f8d4a8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a55c5048>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a55f70b8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a5192278>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4b2b4a8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92ac294518>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92ac2c2198>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4c76b70>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92ac2c2d68>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92ac18be80>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c2b1240>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a5625b70>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4e807f0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4f48cc0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a54b8160>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4e22b38>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4fc05c0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4fc5390>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4e75940>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a57d7a90>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a528e6d8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c384a20>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c564048>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a57d7c50>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a523e320>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a5748828>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a513ddd8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a509ce48>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4ef83c8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4edc278>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c5d24e0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c074eb8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c654518>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c4c8c88>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c6c6438>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c6e06d8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c4844a8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c668c18>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c3100f0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c10be80>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c714fd0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f92a4ee8940>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c10b748>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c51b6a0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c64acc0>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c51bd30>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f927c48fb00>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c221f60>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c426ba8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f929c6066d8>>
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Abgebrochen (Speicherabzug geschrieben)
```
This is pip freeze:
(TransformerTTS) [user1@linux TransformerTTS]$ pip freeze
```
absl-py==0.9.0
astunparse==1.6.3
attrs==19.3.0
audioread==2.1.8
cachetools==4.1.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
clldutils==3.5.2
colorlog==4.1.0
csvw==1.7.0
cycler==0.10.0
decorator==4.4.2
docopt==0.6.2
gast==0.3.3
google-auth==1.17.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.1
isodate==0.6.0
joblib==0.15.1
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
librosa==0.7.2
llvmlite==0.32.1
Markdown==3.2.2
matplotlib==3.2.1
num2words==0.5.10
numba==0.49.1
numpy==1.18.5
oauthlib==3.1.0
opt-einsum==3.2.1
phonemizer==2.1
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
python-dateutil==2.8.1
regex==2020.6.8
requests==2.23.0
requests-oauthlib==1.3.0
resampy==0.2.2
rfc3986==1.4.0
rsa==4.6
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scikit-learn==0.23.1
scipy==1.4.1
segments==2.1.3
six==1.15.0
SoundFile==0.10.3.post1
tabulate==0.8.7
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
threadpoolctl==2.1.0
tqdm==4.46.1
unicode==2.7
uritemplate==3.0.1
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
```
- I am running the script from command line

**Comment by cfrancesco** [comment]
Mh, hard to tell, it doesn't seem to refer to any specific part of the code. I wonder if it has to do with tensorboard or with some specific image (maybe a 0 axis?). Try to change the seed number, if this happens again after 26K step we can likely exclude that it's a specific image breaking this.

**Comment by padmalcom** [comment]
Hi found this one on the internet as well and will try it tonight, thanks.

**Comment by padmalcom** [comment]
This seems to be the solution. I'm at 28.000 steps now and no error so far.
