### ISSUE TITLE
Problem computing alignment dataset

### ISSUE THREAD

**Issue by fathana** [as-ideas/TransformerTTS#34]
Hi,

Thank you for sharing your implementation that I find great. I used your repository to train the first autoregressive model which worked fine and was able to synthesize speech for my sentences. However, when I try to use the autoregressive model to create the durations dataset, folders inside forward_data are created but are empty. When I subsequently try to train the forward model it obviously fails: 

# python train_forward.py --config config/melgan
`TRAINING
Traceback (most recent call last):
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:
      
Traceback (most recent call last):
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "anaconda3/envs/tfenv2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_forward.py", line 122, in <module>
    test_batch = val_dataset.next_batch()
  File "TTS/TransformerTTS/preprocessing/data_handling.py", line 35, in next_batch
    return next(self.data_iter)
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "anaconda3/envs/tfenv2/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 672, in next
    raise StopIteration
StopIteration`

Here is the output during extraction of alignements, where, after checking the extract_durations.py file, I can see that some loops further in the file are not entered (load_files returns full objects for both train and val samples):

# python extract_durations.py --config config/melgan --binary --fix_jumps --fill_mode_next
`2020-07-02 13:08:56.878490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10368 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:68:00.0, compute capability: 6.1)
^M0it [00:00, ?it/s]^MProcessing validation set: : 0it [00:00, ?it/s]2020-07-02 13:09:09.360962: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-02 13:09:10.055624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
^MProcessing validation set: : 1it [00:12, 12.81s/it]^MProcessing validation set: : 1it [00:13, 12.81s/it]^MProcessing validation set: : 2it [00:13,  9.11s/it]^MProcessing validation set: : 2it [00:13,  6.65s/it]

^M0it [00:00, ?it/s]^M0it [00:00, ?it/s]
^M0it [00:00, ?it/s]^M0it [00:00, ?it/s]
1 Physical GPUs, 1 Logical GPUs
DurationExtraction_weighted_binary_filled(next)_fix_jumps
restored weights from /LJSpeech/logdir_newTTS_en/melgan/autoregressive_weights/ckpt-90 at step 900000
Extracting attention from layer Decoder_DenseBlock4_CrossAttention
Done.`

My data configuration for MelGAN is:
`data_directory: '/LJSpeech/LJSpeech-1.1' # path to wavs and metafile directory
log_directory: '/LJSpeech/logdir_newTTS_en'   # weights and logs are stored here
train_data_directory: None         # optional: alternative directory where to store processed data (default is data_dir)
wav_subdir_name: 'wavs'            # subfolder in data_directory containing wavs files
metadata_filename: 'metadata.csv'  # name of metadata file under data_directory
session_name: None                 # session naming, can be specified in command line

# DATA
n_samples: 100000
n_test: 100
mel_start_value: 4
mel_end_value: -4

# AUDIO
sampling_rate: 22050
n_fft: 1024
mel_channels: 80
hop_length: 256
win_length: 1024
f_min: 0
f_max: 8000
normalizer: MelGAN                 # which mel normalization to use from utils.audio.py [MelGAN or WaveRNN]
# TOKENIZER
phoneme_language: 'en'`

Could you please help what could be going wrong here ?

**Comment by fathana** [comment]
Problem solved by adding the store_predictions option which eanables to store the model predictions:

`python extract_durations.py --config config/melgan --binary --fix_jumps --fill_mode_next --store_predictions`
