### ISSUE TITLE
Cannot train forward model (StopIteration)

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#42]
Hi, I successfully trained an Autoregressive Model, executed extract_durations.py and now want to train the forward model. Unfortunately, executing `python train_forward.py --config config/melgan` gives me a StopIteration. 

**Edit**: I found out that the folder "forward_data" in my train_data_directory contains four folders "train", "train_predictions_melgan", "val" and "val_predictions_melgan". But all four are empty. I guess "extract_durations.py" should fill them in some way?

This is the end of the stack trace:

```
starting training from scratch


TRAINING
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_forward.py", line 122, in <module>
    test_batch = val_dataset.next_batch()
  File "/home/user1/TransformerTTS/preprocessing/data_handling.py", line 35, in next_batch
    return next(self.data_iter)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 672, in next
    raise StopIteration
StopIteration
```

**Comment by sgokcen** [comment]
I added  "--store_predictions" option to "extract_durations.py" and used:

python3 extract_durations.py --config config/melgan --binary --fix_jumps --fill_mode_next --store_predictions

That seems the to fix the error you are seeing.

**Comment by cfrancesco** [comment]
Hi, yes it was an issue with the script to extract lengths, if the predictions were not stored, it would not save the results and it would iterate through an empty list when training. Should be fixed now.
