### ISSUE TITLE
Invalid array shape in extract_durations

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#43]
Hi thanks for your help with storing predictions in extract_durations. Now that I can run the script, the next error occurs. Any ideas why the shape does not fit? Thanks again!

```
Extracting training alignments: : 156it [06:40,  2.57s/it]
Traceback (most recent call last):
  File "extract_durations.py", line 230, in <module>
    np.save(str(train_target_dir / f'{sample_idx}_mel_phon_dur.npy'), sample)
  File "<__array_function__ internals>", line 6, in save
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/numpy/lib/npyio.py", line 527, in save
    arr = np.asanyarray(arr)
  File "/home/user1/anaconda3/envs/TransformerTTS/lib/python3.7/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (224,80) into shape (224)

```

**Comment by cfrancesco** [comment]
Hi, are you still having this issue?

**Comment by padmalcom** [comment]
Hi Francesco, I'm at 25% of autoregressive training again with the newer version so I can't give you feedback yet. Training will be done in ~two days.
