### ISSUE TITLE
Error during Training

### ISSUE THREAD

**Issue by arsalan993** [as-ideas/TransformerTTS#46]
During the training, I ran the command `!python train_autoregressive.py --config config/melgan`
I am getting following error
```
starting training from scratch

TRAINING
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_autoregressive.py", line 116, in <module>
    _ = train_dataset.next_batch()
  File "/content/TransformerTTS/preprocessing/data_handling.py", line 33, in next_batch
    return next(self.data_iter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 774, in next
    raise StopIteration
StopIteration
```

I made some changes to **create_dataset.py** file since my metadata.csv file hai two columns one is the filename and other is audio _caption while the audio file itself if of **.flac** format. 
Here is sample data from metadata.csv file `84-121123-0000 GO DO YOU HEAR`

**Comment by arsalan993** [comment]
btw i setup everything on google colab

**Comment by wyp1996** [comment]
Hello. Any update on this issue? I encounter the same error.

**Comment by padmalcom** [comment]
see https://github.com/as-ideas/TransformerTTS/issues/42
