### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by Pritzier** [as-ideas/TransformerTTS#54]
When running the following command: `python train_autoregressive.py --config config/wavernn`
I get the error: 

```
starting training from scratch

TRAINING
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\context.py", line 1986, in execution_mode
    yield
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 670, in next
    return self._next_internal()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\context.py", line 1989, in execution_mode
    executor_new.wait()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_autoregressive.py", line 119, in <module>
    _ = train_dataset.next_batch()
  File "E:\dev\TransformerTTS-master\preprocessing\data_handling.py", line 35, in next_batch
    return next(self.data_iter)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 631, in __next__
    return self.next()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 672, in next
    raise StopIteration
StopIteration
```

**Comment by cfrancesco** [comment]
Seems like an empty iterator, check if you're pointing at the right folder and if it contains a 'mels' folder.

**Comment by Pritzier** [comment]
@cfrancesco Ah, my mistake. Thanks!
